{% set name = "dulwich" %}
{% set version = "0.23.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/dulwich-{{ version }}.tar.gz
  sha256: 3d30e11a882817059b134fa9918d2ec5c95c3a3bd2e21034a368cf9e50d27ae3

build:
  entry_points:
    - dulwich = dulwich.cli:main
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('rust') }}
    - {{ stdlib("c") }}
  host:
    - python
    - setuptools >=77.0.0
    - setuptools-rust
    - pip
  run:
    - python
    - urllib3 >=1.25
    - setuptools  # [py >= 312]

test:
  imports:
    - dulwich
    - dulwich.tests
    - dulwich.archive
    - dulwich.client
    - dulwich.config
    - dulwich.diff_tree
    - dulwich.errors
    - dulwich.file
    - dulwich.hooks
    - dulwich.ignore
    - dulwich.index
    - dulwich.object_store
    - dulwich.objects
    - dulwich.objectspec
    - dulwich.pack
    - dulwich.patch
    - dulwich.protocol
    - dulwich.reflog
    - dulwich.refs
    - dulwich.repo
    - dulwich.server
    - dulwich.walk
    - dulwich.web
  commands:
    - pip check
    - dulwich help --all
  requires:
    - pip

about:
  home: https://www.dulwich.io/
  license: Apache-2.0
  license_family: Apache
  license_file: COPYING
  summary: Python Git Library

  description: |
    Python implementation of the Git file formats and protocols, without the need to have git installed.
    All functionality is available in pure Python. Optional C extensions can be built for improved performance.
    The project is named after the part of London that Mr. and Mrs. Git live in in the particular Monty Python sketch.
  doc_url: https://www.dulwich.io/docs/
  dev_url: https://github.com/jelmer/dulwich

extra:
  recipe-maintainers:
    - mikofski
    - xylar
