appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
travis:
  secure: {BINSTAR_TOKEN: ay71j3yEOVAMb1f/h5V/A/XbxjZYqNyl+msDXEazToem98kQNeSq0kKWhIWrjohHSkiQZGZTa3yEFGsPUsu6NuFReNClyANTJX2Xw37ci6KfA0M8DGDPhcMq6S4rmM9ferjp7rZOnkAa/rTcgKYGwzlj+aJF7AUqzSNVaooRG3TSS+U5g8zcHIQyp6UIFxodbQE5rvs9FmJny86uHmk6bGyGe7PyfuX3i+uh5zpFRvMPvIXWOZEmLWZvnAeh19PcN4kWjj3ys0EajFpPg2hXtfGDP0j7SAMPihy3Q6NzWfpTQFzJgp64SnbWLsCnsXS9MTX8exYbfYbFQbedG1mz32I/DBduXOpC5GdFB42ao47b9eW9MFyc4VY3hq+62LWJCT157rLJ6m/RVCe0Ts4NF1GoLpiZaCAmrKoqCup6WH1J4SX06amolUbDZs3RI2ozMqLlDetLc3ZEgSfCCmScbQaExJ5z/m81XTLClfMwdkmZsJUy5V4vvqaXEWiqPsi8RkPjwLJuZCwOGxbbBVwlqsemVp2c2m7D6Zb4VVoDL/JByiKdfqEztUxnj2b28Zoxceute8Wgwcl0Gsbk9Z4wnA7O3gNTGxT2YlS5QyYFHoC+Nvm1CQbD9gEkSKezVUnoC4TcJmzPCR5qS1dxtEvDLB/rWqsH32c1wUxNlZwv3wA=}
provider:
  win: azure
bot:
  automerge: true
